/*
 * export.js -- writes a PVT model out in the formats reservoir simulators read.
 *
 *   eclipse  : ECLIPSE 100 / OPM Flow / tNavigator include file
 *              (DENSITY, PVTO, PVDG, PVTW, ROCK) in FIELD or METRIC units
 *   cmg      : CMG IMEX/GEM black-oil PVT section (*PVT *BG) in FIELD or SI
 *   csv      : full property table, one row per pressure
 *   json     : the complete model, for scripting / QC
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.PVTExport = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  var K = {
    PSI_BAR: 0.0689475729,        /* psi   -> bar      */
    PSI_KPA: 6.89475729,          /* psi   -> kPa      */
    SCFSTB_SM3SM3: 0.178107607,   /* scf/STB -> sm3/sm3 */
    FT3SCF_RBMSCF: 1000 / 5.614583,
    LBFT3_KGM3: 16.0184634,
    BBL_FT3: 5.614583
  };

  function f(x, n) {
    if (x === null || x === undefined || !isFinite(x)) return '';
    return Number(x).toFixed(n === undefined ? 5 : n);
  }
  function pad(s, w) { s = String(s); return s.length >= w ? s : new Array(w - s.length + 1).join(' ') + s; }
  function col(x, n, w) { return pad(f(x, n), w === undefined ? 12 : w); }
  /* Compressibilities and viscosibilities are O(1e-6) - always write them
     in exponential form so no significant figures are lost in the deck. */
  function sci(x, n, w) {
    if (x === null || x === undefined || !isFinite(x)) return pad('', w || 14);
    return pad(Number(x).toExponential(n === undefined ? 5 : n), w === undefined ? 14 : w);
  }

  function stamp(model, comment) {
    var i = model.input, c = i.corr;
    var names = {
      standing: 'Standing (1947)', vasquezBeggs: 'Vasquez & Beggs (1980)',
      glaso: 'Glaso (1980)', alMarhoun: 'Al-Marhoun (1988)',
      petroskyFarshad: 'Petrosky & Farshad (1993)', lasater: 'Lasater (1958)',
      beggsRobinson: 'Beggs & Robinson (1975)', beal: 'Beal (1946)',
      ngEgbogah: 'Ng & Egbogah (1983)', chewConnally: 'Chew & Connally (1959)',
      mccain: 'McCain et al. (1988)', dak: 'Dranchuk & Abou-Kassem (1975)',
      hallYarborough: 'Hall & Yarborough (1973)', beggsBrill: 'Beggs & Brill (1973)',
      sutton: 'Sutton (1985)', wichertAziz: 'Wichert & Aziz (1972)',
      carr: 'Carr, Kobayashi & Burrows (1954)',
      leeGonzalezEakin: 'Lee, Gonzalez & Eakin (1966)',
      carrKobayashiBurrows: 'Carr, Kobayashi & Burrows (1954)', none: 'none'
    };
    var n = function (k) { return names[k] || k; };
    var L = [
      'PVT tables generated by the Black-Oil PVT Generator',
      'Generated (UTC): ' + new Date().toISOString(),
      '',
      'RESERVOIR / FLUID INPUTS',
      '  Reservoir temperature      : ' + f(i.tempF, 1) + ' degF',
      '  Stock-tank oil gravity     : ' + f(i.api, 2) + ' API  (sg = ' + f(141.5 / (i.api + 131.5), 4) + ')',
      '  Solution gas gravity       : ' + f(i.gammaG, 4) + ' (air = 1)',
      '  Solution GOR at Pb (Rsb)   : ' + f(model.rsb, 1) + ' scf/STB',
      '  Bubble-point pressure      : ' + f(model.pb, 1) + ' psia' +
        (model.pbFactor !== 1 ? '  (calibrated; correlation gave ' + f(model.pbCalc, 1) + ' psia)' : ''),
      '  Bo at Pb                   : ' + f(model.bob, 4) + ' bbl/STB' +
        (model.boFactor !== 1 ? '  (calibrated)' : ''),
      '  Oil viscosity at Pb        : ' + f(model.muob, 4) + ' cp',
      '  Separator                  : ' + f(i.pSepPsia, 1) + ' psia @ ' + f(i.tSepF, 1) + ' degF',
      '  Inerts (mol frac)          : CO2 ' + f(i.yCO2, 4) + ', H2S ' + f(i.yH2S, 4) + ', N2 ' + f(i.yN2, 4),
      '  Brine salinity             : ' + f(i.salinity * 1e4, 0) + ' ppm NaCl equivalent (' + f(i.salinity, 3) + ' wt%)',
      '  Pseudo-criticals           : Tpc ' + f(model.pcrit.tpc, 1) + ' degR, Ppc ' + f(model.pcrit.ppc, 1) + ' psia',
      '',
      'CORRELATIONS',
      '  Pb / Rs                    : ' + n(c.pb),
      '  Bo (saturated)             : ' + n(c.bo),
      '  Undersaturated co          : ' + n(c.co),
      '  Dead-oil viscosity         : ' + n(c.muod),
      '  Saturated oil viscosity    : ' + n(c.muob),
      '  Undersaturated oil visc.   : ' + n(c.muou),
      '  Gas pseudo-criticals       : ' + n(c.pcrit) + ' + ' + n(c.inertCorr),
      '  Gas z-factor               : ' + n(c.z),
      '  Gas viscosity              : ' + n(c.mug),
      '  Water properties           : McCain (1991) / Osif (1988)'
    ];
    if (model.warnings.length) {
      L.push('', 'QC WARNINGS');
      model.warnings.forEach(function (w) { L.push('  ! ' + w); });
    }
    L.push('', 'Correlation-based tables are an estimate. Replace with laboratory',
      'PVT data (CCE / DL / separator tests) before final reserves or',
      'full-field simulation work.');
    return L.map(function (l) { return (comment + ' ' + l).replace(/\s+$/, ''); }).join('\n');
  }

  /* Header block for a gas-reservoir model. */
  function stampGas(model, comment) {
    var i = model.input, c = i.corr;
    var names = {
      dak: 'Dranchuk & Abou-Kassem (1975)', hallYarborough: 'Hall & Yarborough (1973)',
      beggsBrill: 'Beggs & Brill (1973)', sutton: 'Sutton (1985)', standing: 'Standing (1977)',
      wichertAziz: 'Wichert & Aziz (1972)', carr: 'Carr, Kobayashi & Burrows (1954)',
      leeGonzalezEakin: 'Lee, Gonzalez & Eakin (1966)',
      carrKobayashiBurrows: 'Carr, Kobayashi & Burrows (1954)'
    };
    var n = function (k) { return names[k] || k; };
    var L = [
      'PVT tables generated by the Black-Oil PVT Generator (gas reservoir)',
      'Generated (UTC): ' + new Date().toISOString(),
      '',
      'RESERVOIR / FLUID INPUTS',
      '  Fluid type                 : ' + (model.gasKind === 'wet' ? 'Wet gas' : 'Dry gas'),
      '  Reservoir temperature      : ' + f(i.tempF, 1) + ' degF',
      '  Separator gas gravity      : ' + f(i.gammaG, 4) + ' (air = 1)'
    ];
    if (model.gasKind === 'wet') {
      L.push('  Condensate-gas ratio (CGR) : ' + f(model.cgr, 2) + ' STB/MMscf  (GOR ' + f(model.ogr, 0) + ' scf/STB)');
      L.push('  Condensate gravity         : ' + f(model.apiC, 2) + ' API');
      L.push('  Reservoir-gas gravity      : ' + f(model.gammaW, 4) + ' (separator gas recombined with condensate)');
    }
    L.push('  Separator                  : ' + f(i.pSepPsia, 1) + ' psia @ ' + f(i.tSepF, 1) + ' degF');
    L.push('  Inerts (mol frac)          : CO2 ' + f(i.yCO2, 4) + ', H2S ' + f(i.yH2S, 4) + ', N2 ' + f(i.yN2, 4));
    L.push('  Brine salinity             : ' + f(i.salinity * 1e4, 0) + ' ppm NaCl equivalent (' + f(i.salinity, 3) + ' wt%)');
    L.push('  Pseudo-criticals           : Tpc ' + f(model.pcrit.tpc, 1) + ' degR, Ppc ' + f(model.pcrit.ppc, 1) + ' psia');
    L.push('  Bg / Eg basis              : reservoir volume per standard volume of SEPARATOR gas');
    L.push('', 'CORRELATIONS',
      '  Gas pseudo-criticals       : ' + n(c.pcrit) + ' + ' + n(c.inertCorr),
      '  Gas z-factor               : ' + n(c.z),
      '  Gas viscosity              : ' + n(c.mug));
    if (model.gasKind === 'wet') {
      L.push('  Recombination              : McCain (1990) well-stream gravity, Mo = 5954/(API - 8.811)');
    }
    L.push('  Water properties           : McCain (1991) / Osif (1988)');
    L.push('', 'SCOPE',
      '  The reservoir is modelled as single-phase gas at every table pressure.',
      '  A dry gas drops no liquid; a wet gas yields its condensate at the',
      '  separator, not in the reservoir. Retrograde gas condensates are out of',
      '  scope - they need a CCE/CVD study or a compositional model.');
    if (model.warnings.length) {
      L.push('', 'QC WARNINGS');
      model.warnings.forEach(function (w) { L.push('  ! ' + w); });
    }
    L.push('', 'Correlation-based tables are an estimate. Replace with laboratory',
      'PVT data before final reserves or full-field simulation work.');
    return L.map(function (l) { return (comment + ' ' + l).replace(/\s+$/, ''); }).join('\n');
  }

  function eclipseGas(model, units) {
    var metric = units === 'metric';
    var i = model.input;
    var cp = function (p) { return metric ? p * K.PSI_BAR : p; };
    var cBg = function (bg) { return metric ? bg : bg * K.FT3SCF_RBMSCF; };
    var cRho = function (d) { return metric ? d * K.LBFT3_KGM3 : d; };
    var cComp = function (x) { return metric ? x / K.PSI_BAR : x; };
    var uP = metric ? 'barsa' : 'psia';
    var uBo = metric ? 'rm3/sm3' : 'rb/STB';
    var uBg = metric ? 'rm3/sm3' : 'rb/Mscf';
    var uRho = metric ? 'kg/m3' : 'lb/ft3';
    var uC = metric ? '1/bar' : '1/psi';
    var L = [];
    L.push(stampGas(model, '--'));
    L.push('');
    L.push('-- RUNSPEC phases: GAS WATER (no oil phase in the reservoir)');
    if (model.gasKind === 'wet') {
      L.push('-- Wet gas: Bg is on the separator-gas basis, so surface condensate');
      L.push('-- = gas rate x CGR (' + f(model.cgr, 2) + ' STB/MMscf).');
    }
    L.push('');
    L.push(metric ? 'METRIC' : 'FIELD');
    L.push('');
    L.push('-- Surface densities: oil (' + (model.gasKind === 'dry' ? 'placeholder' : 'stock-tank condensate') +
      ') / water / gas (' + uRho + ')');
    L.push('DENSITY');
    L.push('  ' + col(cRho(model.rhoOsc), 4) + col(cRho(model.rhoWsc), 4) + col(cRho(model.rhoGsc), 6) + ' /');
    L.push('/');
    L.push('');
    L.push('-- ' + (model.gasKind === 'wet' ? 'Wet' : 'Dry') + ' gas: P (' + uP + ')  Bg (' + uBg + ')  Visc (cP)');
    L.push('PVDG');
    model.gas.forEach(function (g) {
      L.push('  ' + col(cp(g.p), 3, 12) + col(cBg(g.bg), 6, 14) + col(g.mug, 6, 12));
    });
    L.push('/');
    L.push('');
    var wRef = model.water[Math.floor(model.water.length / 2)];
    var wHi = model.water[model.water.length - 1];
    var visc = (wHi.muw - wRef.muw) / Math.max(wHi.p - wRef.p, 1e-9) / wRef.muw;
    L.push('-- Water: Pref (' + uP + ')  Bw (' + uBo + ')  Cw (' + uC + ')  Visc (cP)  Viscosibility (' + uC + ')');
    L.push('PVTW');
    L.push('  ' + col(cp(wRef.p), 3, 12) + col(wRef.bw, 5, 12) + sci(cComp(wRef.cw), 5, 14) +
      col(wRef.muw, 5, 12) + sci(cComp(visc), 5, 14) + ' /');
    L.push('');
    L.push('-- Rock: Pref (' + uP + ')  Cr (' + uC + ')');
    L.push('ROCK');
    L.push('  ' + col(cp(i.pRefRock), 3, 12) + sci(cComp(i.rockComp), 5, 14) + ' /');
    L.push('');
    return L.join('\n');
  }

  /* ------------------------------------------------------------------ */
  /* CMG IMEX -- gas reservoirs                                          */
  /*                                                                     */
  /*   dry gas  *MODEL *GASWATER                 *PVTG      p, Eg, visg  */
  /*   wet gas  *MODEL *GASWATER_WITH_CONDENSATE *PVTG *RV  p, Eg, Rv,   */
  /*                                                            visg     */
  /*                                                                     */
  /* Eg is a volume ratio (reservoir volume per standard volume), so the */
  /* same number serves FIELD and SI; only p, Rv and the densities and   */
  /* compressibilities change with the unit system.                      */
  /* ------------------------------------------------------------------ */
  function cmgGas(model, units) {
    var si = units === 'metric';
    var i = model.input, wet = model.gasKind === 'wet';
    var cp = function (p) { return si ? p * K.PSI_KPA : p; };
    var cRho = function (d) { return si ? d * K.LBFT3_KGM3 : d; };
    /* STB/MMscf -> sm3/sm3 for SI, left as STB/MMscf in FIELD */
    var cRv = function (rv) { return si ? rv * K.BBL_FT3 / 1e6 : rv; };
    var uP = si ? 'kPa' : 'psi';
    var uRho = si ? 'kg/m3' : 'lb/ft3';
    var uRv = si ? 'm3/m3' : 'STB/MMscf';
    var L = [];

    L.push(stampGas(model, '**'));
    L.push('');
    L.push(si ? '*INUNIT *SI' : '*INUNIT *FIELD');
    L.push('');
    L.push('*MODEL ' + (wet ? '*GASWATER_WITH_CONDENSATE  ** gas, water and surface condensate'
                             : '*GASWATER                  ** two-phase gas and water'));
    L.push('');
    L.push('** Reference densities at standard surface conditions (' + uRho + ')');
    L.push('*RESERVOIR *GAS');
    if (wet) L.push('*DENSITY *OIL   ' + f(cRho(model.rhoOsc), 4) + '   ** stock-tank condensate');
    L.push('*DENSITY *GAS   ' + f(cRho(model.rhoGsc), 5));
    L.push('*DENSITY *WATER ' + f(cRho(model.rhoWsc), 4));
    L.push('');
    L.push('** ' + (wet ? 'Wet' : 'Dry') + ' gas PVT table vs pressure. Eg is a volume ratio:');
    L.push('** reservoir volume per standard volume of SEPARATOR gas (Eg = 1/Bg).');
    if (wet) {
      L.push('** Rv is the vaporised condensate the gas carries, constant at the CGR:');
      L.push('** a wet gas never drops liquid in the reservoir.');
      L.push('*PVTG *RV');
      L.push('**' + pad('P (' + uP + ')', 12) + pad('Eg (vol/vol)', 16) +
        pad('Rv (' + uRv + ')', 16) + pad('visg (cp)', 12));
      model.gas.forEach(function (g) {
        L.push('  ' + col(cp(g.p), 2, 12) + col(g.eg, 4, 16) +
          (si ? sci(cRv(g.rv), 5, 16) : col(cRv(g.rv), 4, 16)) + col(g.mug, 6, 12));
      });
    } else {
      L.push('*PVTG');
      L.push('**' + pad('P (' + uP + ')', 12) + pad('Eg (vol/vol)', 16) + pad('visg (cp)', 12));
      model.gas.forEach(function (g) {
        L.push('  ' + col(cp(g.p), 2, 12) + col(g.eg, 4, 16) + col(g.mug, 6, 12));
      });
    }
    L.push('');
    var wRef = model.water[Math.floor(model.water.length / 2)];
    var wHi = model.water[model.water.length - 1];
    var cvw = (wHi.muw - wRef.muw) / Math.max(wHi.p - wRef.p, 1e-9);
    L.push('** Water properties at reference pressure');
    L.push('*REFPW ' + f(cp(wRef.p), 2));
    L.push('*BWI   ' + f(wRef.bw, 5));
    L.push('*CW    ' + (si ? (wRef.cw / K.PSI_KPA).toExponential(4) : wRef.cw.toExponential(4)));
    L.push('*VWI   ' + f(wRef.muw, 5));
    L.push('*CVW   ' + (si ? (cvw / K.PSI_KPA).toExponential(4) : cvw.toExponential(4)));
    L.push('');
    L.push('** Rock compressibility (reservoir section)');
    L.push('*CPOR  ' + (si ? (i.rockComp / K.PSI_KPA).toExponential(4) : i.rockComp.toExponential(4)));
    L.push('*PRPOR ' + f(cp(i.pRefRock), 2));
    L.push('');
    return L.join('\n');
  }

  function csvGas(model) {
    var L = [];
    stampGas(model, '#').split('\n').forEach(function (l) { L.push(l); });
    L.push('');
    L.push(['Pressure_psia', 'Z_factor', 'Bg_ft3_scf', 'Bg_rb_Mscf', 'Bg_wellstream_ft3_scf',
      'Eg_scf_ft3', 'mug_cp', 'rho_g_lbft3', 'cg_1_psi', 'Rv_STB_MMscf',
      'Bw_bbl_STB', 'muw_cp', 'cw_1_psi', 'rho_w_lbft3'].join(','));
    model.gas.forEach(function (g, k) {
      var w = model.water[k];
      L.push([f(g.p, 2), f(g.z, 5), f(g.bg, 6), f(g.bgRbMscf, 5), f(g.bgw, 6),
        f(g.eg, 3), f(g.mug, 6), f(g.rhoG, 5), g.cg.toExponential(5), f(g.rv, 4),
        f(w.bw, 5), f(w.muw, 5), w.cw.toExponential(5), f(w.rhoW, 4)].join(','));
    });
    return L.join('\n');
  }

  /* ------------------------------------------------------------------ */
  /* ECLIPSE / OPM Flow / tNavigator                                     */
  /* ------------------------------------------------------------------ */
  function eclipse(model, units) {
    var metric = units === 'metric';
    var i = model.input;
    var cp = function (p) { return metric ? p * K.PSI_BAR : p; };
    var cRs = function (r) { return metric ? r * K.SCFSTB_SM3SM3 : r / 1000; };  /* METRIC sm3/sm3, FIELD Mscf/STB */
    var cBg = function (bg) { return metric ? bg : bg * K.FT3SCF_RBMSCF; };      /* METRIC rm3/sm3, FIELD rb/Mscf  */
    var cRho = function (d) { return metric ? d * K.LBFT3_KGM3 : d; };
    var cComp = function (x) { return metric ? x / K.PSI_BAR : x; };            /* 1/psi -> 1/bar */
    var uP = metric ? 'barsa' : 'psia';
    var uRs = metric ? 'sm3/sm3' : 'Mscf/STB';
    var uBo = metric ? 'rm3/sm3' : 'rb/STB';
    var uBg = metric ? 'rm3/sm3' : 'rb/Mscf';
    var uRho = metric ? 'kg/m3' : 'lb/ft3';
    var uC = metric ? '1/bar' : '1/psi';
    var L = [];

    L.push(stamp(model, '--'));
    L.push('');
    L.push(metric ? 'METRIC' : 'FIELD');
    L.push('');
    L.push('-- Surface densities: oil / water / gas (' + uRho + ')');
    L.push('DENSITY');
    L.push('  ' + col(cRho(model.rhoOsc), 4) + col(cRho(model.rhoWsc), 4) + col(cRho(model.rhoGsc), 6) + ' /');
    L.push('/');
    L.push('');
    L.push('-- Live oil: Rs (' + uRs + ')  Pbub (' + uP + ')  Bo (' + uBo + ')  Visc (cP)');
    L.push('-- Each record: the saturated node first, then its undersaturated branch.');
    L.push('PVTO');
    model.pvto.forEach(function (rec) {
      rec.rows.forEach(function (r, k) {
        var head = k === 0 ? col(cRs(rec.rs), 6, 12) : pad('', 12);
        L.push('  ' + head + col(cp(r.p), 3, 12) + col(r.bo, 5, 12) + col(r.muo, 5, 12) +
          (k === rec.rows.length - 1 ? ' /' : ''));
      });
    });
    L.push('/');
    L.push('');
    L.push('-- Dry gas: P (' + uP + ')  Bg (' + uBg + ')  Visc (cP)');
    L.push('PVDG');
    model.gas.forEach(function (g) {
      L.push('  ' + col(cp(g.p), 3, 12) + col(cBg(g.bg), 6, 14) + col(g.mug, 6, 12));
    });
    L.push('/');
    L.push('');
    var wRef = model.water[Math.floor(model.water.length / 2)];
    var wHi = model.water[model.water.length - 1];
    var visc = (wHi.muw - wRef.muw) / Math.max(wHi.p - wRef.p, 1e-9) / wRef.muw;
    L.push('-- Water: Pref (' + uP + ')  Bw (' + uBo + ')  Cw (' + uC + ')  Visc (cP)  Viscosibility (' + uC + ')');
    L.push('PVTW');
    L.push('  ' + col(cp(wRef.p), 3, 12) + col(wRef.bw, 5, 12) + sci(cComp(wRef.cw), 5, 14) +
      col(wRef.muw, 5, 12) + sci(cComp(visc), 5, 14) + ' /');
    L.push('');
    L.push('-- Rock: Pref (' + uP + ')  Cr (' + uC + ')');
    L.push('ROCK');
    L.push('  ' + col(cp(i.pRefRock), 3, 12) + sci(cComp(i.rockComp), 5, 14) + ' /');
    L.push('');
    return L.join('\n');
  }

  /* ------------------------------------------------------------------ */
  /* CMG IMEX / GEM                                                      */
  /* ------------------------------------------------------------------ */
  function cmg(model, units) {
    var si = units === 'metric';
    var i = model.input;
    var cp = function (p) { return si ? p * K.PSI_KPA : p; };
    var cRs = function (r) { return si ? r * K.SCFSTB_SM3SM3 : r; };             /* FIELD ft3/bbl */
    var cEg = function (bg) { return si ? 1 / bg : K.BBL_FT3 / bg; };            /* FIELD scf/bbl, SI sm3/m3 */
    var cRho = function (d) { return si ? d * K.LBFT3_KGM3 : d; };
    var cComp = function (x) { return si ? x / K.PSI_KPA : x; };                 /* 1/psi -> 1/kPa */
    var uP = si ? 'kPa' : 'psia';
    var uRs = si ? 'm3/m3' : 'ft3/bbl';
    var uEg = si ? 'm3/m3' : 'ft3/bbl';
    var uRho = si ? 'kg/m3' : 'lb/ft3';
    var L = [];

    L.push(stamp(model, '**'));
    L.push('');
    L.push(si ? '*INUNIT *SI' : '*INUNIT *FIELD');
    L.push('');
    L.push('*MODEL *BLACKOIL');
    L.push('');
    L.push('** Saturated PVT table (undersaturated behaviour from *CO / *CVO below)');
    L.push('**' + pad('p (' + uP + ')', 12) + pad('rs (' + uRs + ')', 14) +
      pad('bo (m3/m3)', 14) + pad('eg (' + uEg + ')', 14) +
      pad('viso (cp)', 12) + pad('visg (cp)', 12));
    L.push('*PVT *BG 1');
    model.oil.forEach(function (o, k) {
      if (!o.saturated) return;
      var g = model.gas[k];
      L.push('  ' + col(cp(o.p), 2, 12) + col(cRs(o.rs), 4, 14) + col(o.bo, 5, 14) +
        col(cEg(g.bg), 4, 14) + col(o.muo, 5, 12) + col(g.mug, 6, 12));
    });
    /* the saturation pressure must be the last entry of the saturated table */
    L.push('');
    L.push('** Undersaturated oil: compressibility and viscosity gradient at Pb');
    var last = model.oil[model.oil.length - 1];
    var cvo = last.saturated ? 0 : (last.muo - model.muob) / Math.max(last.p - model.pb, 1e-9);
    L.push('*CO   ' + (si ? (model.cob / K.PSI_KPA).toExponential(4) : model.cob.toExponential(4)));
    L.push('*CVO  ' + (si ? (cvo / K.PSI_KPA).toExponential(4) : cvo.toExponential(4)));
    L.push('');
    L.push('** Surface densities (' + uRho + ')');
    L.push('*DENSITY *OIL   ' + f(cRho(model.rhoOsc), 4));
    L.push('*DENSITY *GAS   ' + f(cRho(model.rhoGsc), 5));
    L.push('*DENSITY *WATER ' + f(cRho(model.rhoWsc), 4));
    L.push('');
    var wRef = model.water[Math.floor(model.water.length / 2)];
    var wHi = model.water[model.water.length - 1];
    var cvw = (wHi.muw - wRef.muw) / Math.max(wHi.p - wRef.p, 1e-9);
    L.push('** Water properties at reference pressure');
    L.push('*REFPW ' + f(cp(wRef.p), 2));
    L.push('*BWI   ' + f(wRef.bw, 5));
    L.push('*CW    ' + (si ? (wRef.cw / K.PSI_KPA).toExponential(4) : wRef.cw.toExponential(4)));
    L.push('*VWI   ' + f(wRef.muw, 5));
    L.push('*CVW   ' + (si ? (cvw / K.PSI_KPA).toExponential(4) : cvw.toExponential(4)));
    L.push('');
    L.push('** Rock compressibility (reservoir section)');
    L.push('*CPOR  ' + (si ? (i.rockComp / K.PSI_KPA).toExponential(4) : i.rockComp.toExponential(4)));
    L.push('*PRPOR ' + f(cp(i.pRefRock), 2));
    L.push('');
    return L.join('\n');
  }

  /* ------------------------------------------------------------------ */
  /* CSV + JSON                                                          */
  /* ------------------------------------------------------------------ */
  function csv(model) {
    var L = [];
    stamp(model, '#').split('\n').forEach(function (l) { L.push(l); });
    L.push('');
    L.push(['Pressure_psia', 'Phase_state', 'Rs_scf_STB', 'Bo_bbl_STB', 'muo_cp',
      'rho_o_lbft3', 'co_1_psi', 'Z_factor', 'Bg_ft3_scf', 'Bg_rb_Mscf', 'Eg_scf_ft3',
      'mug_cp', 'rho_g_lbft3', 'cg_1_psi', 'Bw_bbl_STB', 'muw_cp', 'cw_1_psi',
      'rho_w_lbft3'].join(','));
    model.oil.forEach(function (o, k) {
      var g = model.gas[k], w = model.water[k];
      L.push([f(o.p, 2), o.saturated ? 'saturated' : 'undersaturated', f(o.rs, 3),
        f(o.bo, 5), f(o.muo, 5), f(o.rhoO, 4), o.co === null ? '' : o.co.toExponential(5),
        f(g.z, 5), f(g.bg, 6), f(g.bgRbMscf, 5), f(g.eg, 3), f(g.mug, 6), f(g.rhoG, 5),
        g.cg.toExponential(5), f(w.bw, 5), f(w.muw, 5), w.cw.toExponential(5),
        f(w.rhoW, 4)].join(','));
    });
    return L.join('\n');
  }

  function json(model) { return JSON.stringify(model, null, 2); }

  function generate(model, format, units) {
    if (model.fluid === 'gas') {
      switch (format) {
        case 'eclipse': return eclipseGas(model, units);
        case 'cmg': return cmgGas(model, units);
        case 'csv': return csvGas(model);
        case 'json': return json(model);
        default: throw new Error('Unknown export format: ' + format);
      }
    }
    switch (format) {
      case 'eclipse': return eclipse(model, units);
      case 'cmg': return cmg(model, units);
      case 'csv': return csv(model);
      case 'json': return json(model);
      default: throw new Error('Unknown export format: ' + format);
    }
  }

  function filename(format, units) {
    return {
      eclipse: 'PVT_' + (units === 'metric' ? 'metric' : 'field') + '.INC',
      cmg: 'PVT_imex_' + (units === 'metric' ? 'si' : 'field') + '.dat',
      csv: 'pvt_properties.csv',
      json: 'pvt_model.json'
    }[format];
  }

  return { generate: generate, filename: filename, eclipse: eclipse, cmg: cmg, csv: csv, json: json,
           eclipseGas: eclipseGas, cmgGas: cmgGas, csvGas: csvGas };
});
